### ISSUE TITLE
Only shows Celsius in Homekit

### ISSUE THREAD

**Issue by sieteunoseis** [nitaybz/homebridge-sensibo-ac#5] opened 2020-05-16 09:07 UTC
Sensibo is set to F but HomeKit shows in Celsius

**Comment by nstefanelli** [comment] 2020-05-20 02:48
Also seeing this issue. Confirmed HomeKit is set, Sensibo set in the app for me to F as well.

**Comment by nitaybz** [comment] 2020-05-21 09:18
Hey Guys... please install the latest version and report back :)
thanks

**Comment by bnaturalpa** [comment] 2020-05-21 12:47
Looks like that fixed it, thanks

**Comment by nitaybz** [comment] 2020-06-01 10:28
Please test the latest 1.0.11

**Comment by nitaybz** [comment] 2020-06-05 07:12
Closing and continuing in #8 which is a duplicate

**Comment by nitaybz** [comment] 2020-06-05 07:12
the issue should be solved anyway

**Closed by nitaybz** 2020-06-05 07:12 UTC
