### ISSUE TITLE
HAP Warning in Log

### ISSUE THREAD

**Issue by galrozov** [nitaybz/homebridge-sensibo-ac#21] opened 2020-07-01 14:41 UTC
When the plugin is initialized in the log it issue the following warning:

[SensiboAC] Initializing platform accessory "Bedroom AC"...
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by nitaybz** [comment] 2020-07-01 17:41
This is not an error but a warning.... and also a duplicate of #18
Closing....

**Closed** 2020-07-01 17:41 UTC
