### ISSUE TITLE
Urgent: homebridge-sensibo-ac is breaking other plug-ins

### ISSUE THREAD

**Issue by adriancable** [nitaybz/homebridge-sensibo-ac#48] opened 2021-03-02 22:23 UTC
Dear @nitaybz - I was unable to find your email to get hold of you directly so hopefully this reaches you.

I'm the developer of homebridge-nest, and it was brought to my attention that HOOBS users who install homebridge-sensibo-ac then experience failed API requests in other plug-ins including homebridge-nest (although homebridge-sensibo-ac continues to work fine). After some digging the cause turns out to be that you are modifying parameters of the global Axios object, which on HOOBS is shared across plug-ins. You are doing something like:

		axios.defaults.params = {
			integration: integrationName,
			apiKey: platform.apiKey
		}

The result is that these then get added to the query string for ALL Axios calls that other plug-ins make. You can imagine this might cause serious problems and it does.

If you want to set defaults on Axios you should create your own instance of the object and modify them there, instead of changing properties of the global object.

I (along with lots of other developers of plug-ins on HOOBS) would be enormously grateful if you could fix this!

**Comment by nitaybz** [comment] 2021-03-02 22:32
I didn't know that it's shared among other plugins in hoobs since I don't have that machine... but I'll surely fix it... I'll try to find some time next week.

But if you want to create a pull request I'll merge it earlier.

Thanks for the notice

**Comment by adriancable** [comment] 2021-03-02 22:37
@nitaybz - thanks so much for the speedy response!

I don't have a Sensibo AC system, so it would be difficult for me to test. So I am reluctant to make a PR. But I think the fix is as follows: just change the first line of api.js from:

`const axios = require('axios')`

to:

`const axiosLib = require('axios');
let axios = axiosLib.create();`

**Comment by jsalva23** [comment] 2021-03-03 01:03
Hey @nitaybz thanks for your answer. I'm one of the users who reported the problem to @adriancable since that's was the plug-in reporting the error. The Sensibo plug-in is great and I use it every day but it's now breaking two other plug-ins I frequently use as well. 

Really appreciate your help fixing this issue.

**Comment by nitaybz** [comment] 2021-03-03 20:37
should be fixed now on version 2.1.1

**Comment by nitaybz** [comment] 2021-03-03 20:40
Thanks to you guys I've also fixed a few other plugins of mine...

**Comment by adriancable** [comment] 2021-03-03 20:47
@jsalva23 - I am not 100% sure how HOOBS updates work, but can you see if HOOBS will pick up the 2.1.1 update for homebridge-sensibo-ac, and if so, if it fixes the issue? Thanks!

**Comment by nitaybz** [comment] 2021-03-03 20:50
it seems like it's already updated in HOOBS registry:
https://plugins.hoobs.org/plugin/homebridge-sensibo-ac

**Comment by jsalva23** [comment] 2021-03-03 20:55
@nitaybz Thanks a lot for updating the plugin with the fix @adriancable I can confirm that the new version of the plugin does fix the problem, I'm not getting the 400 error from the Nest plugin anymore and both plugins seems to be working ok now.

Thank you both for your help, awesome response time.

**Comment by jsalva23** [comment] 2021-03-03 20:56
Hoobs does not show the update right away, I had to reboot the raspberry pi for the update to show up, not sure how frequently they refresh for updates.

Thanks again

**Closed by jsalva23** 2021-03-03 20:56 UTC
