### ISSUE TITLE
The target temperature shown In Homekit is off

### ISSUE THREAD

**Issue by ArnaudE** [nitaybz/homebridge-sensibo-ac#8] opened 2020-05-30 17:28 UTC
Hi,
For some reason the target temperature shown in homekit is very high compared to the actual temperature in Sensibo app/on the AC unit.
In the screenshot of the HomeKit settings, it shows 149 degrees (actual target temp shown in Sensibo is 65 degrees (Fahrenheit)).
72 degrees Fahrenheit in the app would display 162 degrees in HomeKit. Therefore, there doesn’t seem to be a linear relationship between the actual number and the one displayed in HomeKit.

![2923CF53-A1A6-41CE-9DF7-FC18D0A7365A](https://user-images.githubusercontent.com/47265222/83335197-f5183100-a278-11ea-9a52-40af919a15aa.jpeg)

**Comment by inari8142** [comment] 2020-05-31 02:34
I had the same problem.  On a whim, I went into the Sensibo app on my iPhone and changed it over to celsius.  That fixed it.  The device in HomeKit is still showing Fahrenheit, but is now the correct "set to" temperature, not 149 degrees.

**Comment by nitaybz** [comment] 2020-05-31 10:10
Hey Guys!
Please try to install the latest @1.0.7

Let me know if it helps, I want to solve the Fahrenheit issue and I need your help debugging it if the issue still persist...

**Comment by inari8142** [comment] 2020-05-31 16:34
Hi!  I updated to your latest version @v1.0.8.  That seems to have fixed it!  Note for anyone else reading the thread: after setting the Sensibo app back to Fahrenheit, I had to restart the Homebridge for the changes to be reflected.

Thanks @nitaybz!

**Comment by inari8142** [comment] 2020-05-31 16:42
Update: sorry - I may have spoken too soon - the temperatures are correct (no longer in the 100+ degrees), but it's opposite of the preference for the Sensibo app.  So, if I have Sensibo in Celsius, HomeKit shows Fahrenheit.  If Sensibo is in Fahrenheit, the Homekit shows Celsius.

**Comment by ArnaudE** [comment] 2020-05-31 19:57
Same here. And when switching back to Fahrenheit in Sensibo, HomeKit becomes Celsius again. I don’t really mind though because I am not using sensibo app that much.

**Comment by nitaybz** [comment] 2020-06-01 09:20
Hey Guys! @ArnaudE @inari8142 

I think I got it this time... please install the latest  (@1.0.9) and test it thoroughly

**Comment by nitaybz** [comment] 2020-06-05 07:13
Hey Guys! @ArnaudE @inari8142 @jakemhiller 
Please update if Fahrenheit works as expected and if we can close this issue

**Comment by jakemhiller** [comment] 2020-06-05 23:49
The target temperature is still off, I’m working on a PR to fix it. I think the problem is that there are still some Fahrenheit temperatures being sent to HomeKit, which always wants the temp in Celsius.

**Comment by nitaybz** [comment] 2020-06-06 06:11
Please check the latest 1.1.8

**Comment by nitaybz** [comment] 2020-06-06 06:15
@jakemhiller if it doesn't work, I have one more thing to try. The mom and max temperature are set in Fahrenheit... but I can change that if the recent fix doesn't work

**Comment by jakemhiller** [comment] 2020-06-06 21:28
Sounds good, trying it now

**Comment by ArnaudE** [comment] 2020-06-06 22:36
Still have the issue on my side with 1.1.7

**Comment by jakemhiller** [comment] 2020-06-07 01:29
@nitaybz sorry, didn't see your message about switching the min/max temps from Fahrenheit, that is what the issue was. I fixed it in #12 along with a couple other smaller things.

**Comment by nitaybz** [comment] 2020-06-07 05:52
the issue should be fixed now thanks to @jakemhiller ... please update to the latest 1.1.8 and let me know if I can close the issue

**Comment by jakemhiller** [comment] 2020-06-07 15:21
Works great for me now! @ArnaudE any luck?

**Comment by ArnaudE** [comment] 2020-06-07 18:27
Works great too! Thanks a lot

**Comment by nitaybz** [comment] 2020-06-07 18:49
🙏🏼

**Closed** 2020-06-07 18:49 UTC
