### ISSUE TITLE
dry e fan active, crash plugin

### ISSUE THREAD

**Issue by Cipa28** [nitaybz/homebridge-sensibo-ac#6] opened 2020-05-27 17:00 UTC
hi, the plugin crashes when i activate dry and fan mode from the json file, or if i am active and i turn on my AC when i go to change fan or the plugin stops working.
[all active.txt](https://github.com/nitaybz/homebridge-sensibo-ac/files/4690284/all.active.txt)

**Comment by nitaybz** [comment] 2020-05-31 10:17
Hey man!
Thanks for your feedback, Please install the latest @1.0.8 and let me know please

**Comment by Cipa28** [comment] 2020-05-31 13:17
> Hey man!
> Thanks for your feedback, Please install the latest @1.0.8 and let me know please

installed the latest version 1.0.8, now it seems to work without crash: D great job!
another thing my AC in dry mode supports temperature regulation, in the sensibo app I can adjust it, but in homekit the possibility of varying the temperature in dry mode is not displayed.
What do I need to provide you to find a solution?

**Comment by nitaybz** [comment] 2020-05-31 13:46
Glad it solved it...
Not sure how to solve your request... first, I don't see how temperature is related to DRY mode, how would changing the temperature will affect the DRY mode on the AC?
second, there is no possibility in HomeKit to set temperature picker in the humidifier/dehumidifier accessory so I'm not completely sure if it's even possible.

**Comment by nitaybz** [comment] 2020-06-01 10:29
closing since the issue is actually resolved... If you want to further discuss your other request, please open a new issue

**Closed by nitaybz** 2020-06-01 10:29 UTC
