### ISSUE TITLE
Homebridge error

### ISSUE THREAD

**Issue by DaveGraham123456** [nitaybz/homebridge-sensibo-ac#85] opened 2022-06-12 23:33 UTC
I have slowness in my homebridge, I went to the status page, and the logs show the following.

[13/06/2022, 09:32:53] [homebridge-sensibo-ac] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.
[13/06/2022, 09:32:53] [homebridge-sensibo-ac] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.

**Comment by ovq** [comment] 2022-07-04 15:24
This is a long standing issue. See [here](https://github.com/nitaybz/homebridge-sensibo-ac/issues/63). 
So far, we are yet waiting for a fix. 

I doubt however, that this would actually slow down your homebridge. To me it's rather cosmetic. I don't see any negative impact.

**Comment by benwebbbenwebb** [comment] 2022-12-20 14:11
Closed as duplicate of #63

**Closed as not planned by benwebbbenwebb** 2022-12-20 14:11 UTC
